export const INTERESTS_OPTIONS = [
  // 🎮 Entertainment & Media
  { name: "Movies", value: "movies", icon: "🍿" },
  { name: "TV Shows", value: "tv_shows", icon: "📺" },
  { name: "Video Games", value: "video_games", icon: "🎮" },
  { name: "Anime", value: "anime", icon: "🌸" },
  { name: "Podcasts", value: "podcasts", icon: "🎧" },
  { name: "Books", value: "books", icon: "📖" },
  { name: "Comics", value: "comics", icon: "🦸" },
  { name: "Stand-up Comedy", value: "standup_comedy", icon: "🎙️" },

  // 🌍 Lifestyle & Social
  { name: "Travel", value: "travel", icon: "🌍" },
  { name: "Foodie", value: "foodie", icon: "🍔" },
  { name: "Coffee Lover", value: "coffee", icon: "☕" },
  { name: "Night Owl", value: "night_owl", icon: "🌙" },
  { name: "Early Riser", value: "early_riser", icon: "🌅" },
  { name: "Partying", value: "partying", icon: "🎉" },
  { name: "Fitness", value: "fitness", icon: "🏋️" },
  { name: "Yoga", value: "yoga", icon: "🧘" },
  { name: "Meditation", value: "meditation", icon: "🧘‍♂️" },
  { name: "Volunteering", value: "volunteering", icon: "🤝" },

  // 🧠 Academic Interests
  { name: "Science", value: "science", icon: "🔬" },
  { name: "Technology", value: "technology", icon: "💻" },
  { name: "Engineering", value: "engineering", icon: "🛠️" },
  { name: "Mathematics", value: "mathematics", icon: "📐" },
  { name: "Literature", value: "literature", icon: "📚" },
  { name: "Philosophy", value: "philosophy", icon: "🤔" },
  { name: "Psychology", value: "psychology", icon: "🧠" },
  { name: "Business", value: "business", icon: "📈" },
  { name: "Politics", value: "politics", icon: "🏛️" },
  { name: "Art History", value: "art_history", icon: "🖼️" },

  // 🎨 Creative & Arts
  { name: "Photography", value: "photography", icon: "📸" },
  { name: "Painting", value: "painting", icon: "🎨" },
  { name: "Graphic Design", value: "graphic_design", icon: "🖌️" },
  { name: "Writing", value: "writing", icon: "✍️" },
  { name: "Theater", value: "theater", icon: "🎭" },
  { name: "Music", value: "music", icon: "🎶" },
  { name: "Singing", value: "singing", icon: "🎤" },
  { name: "Dance", value: "dance", icon: "💃" },
  { name: "Filmmaking", value: "filmmaking", icon: "🎬" },

  // 🐾 Hobbies & Outdoor
  { name: "Hiking", value: "hiking", icon: "🥾" },
  { name: "Camping", value: "camping", icon: "🏕️" },
  { name: "Biking", value: "biking", icon: "🚴" },
  { name: "Skating", value: "skating", icon: "🛹" },
  { name: "Board Games", value: "board_games", icon: "🎲" },
  { name: "Cooking", value: "cooking", icon: "🍳" },
  { name: "Baking", value: "baking", icon: "🧁" },
  { name: "Pet Lover", value: "pets", icon: "🐶" },
  { name: "Gardening", value: "gardening", icon: "🪴" },
  { name: "Thrifting", value: "thrifting", icon: "🛍️" },

  // 🧬 Personality & Vibe
  { name: "Introvert", value: "introvert", icon: "😌" },
  { name: "Extrovert", value: "extrovert", icon: "😄" },
  { name: "Ambivert", value: "ambivert", icon: "😎" },
  { name: "Bookworm", value: "bookworm", icon: "📚" },
  { name: "Adventurous", value: "adventurous", icon: "🧭" },
  { name: "Chill Vibes", value: "chill", icon: "😌" },
  { name: "Spiritual", value: "spiritual", icon: "🔮" },
  { name: "Romantic", value: "romantic", icon: "💘" },
  { name: "Ambitious", value: "ambitious", icon: "🚀" },
  { name: "Funny", value: "funny", icon: "😂" },
];

export const ARTISTS_OPTIONS = [
  { value: "taylor_swift", label: "Taylor Swift" },
  { value: "drake", label: "Drake" },
  { value: "adele", label: "Adele" },
  { value: "kendrick_lamar", label: "Kendrick Lamar" },
  { value: "billie_eilish", label: "Billie Eilish" },
  { value: "ed_sheeran", label: "Ed Sheeran" },
  { value: "rihanna", label: "Rihanna" },
  { value: "post_malone", label: "Post Malone" },
  { value: "the_weeknd", label: "The Weeknd" },
  { value: "dua_lipa", label: "Dua Lipa" },
  { value: "bruno_mars", label: "Bruno Mars" },
  { value: "sza", label: "SZA" },
  { value: "harry_styles", label: "Harry Styles" },
  { value: "justin_bieber", label: "Justin Bieber" },
  { value: "lizzo", label: "Lizzo" },
  { value: "ariana_grande", label: "Ariana Grande" },
  { value: "coldplay", label: "Coldplay" },
  { value: "beyonce", label: "Beyoncé" },
  { value: "lady_gaga", label: "Lady Gaga" },
  { value: "edm_david_guetta", label: "David Guetta" },
];
